Encryption added to the backup
B3Partners/docker-backup pull request #2
Opened 2024-05-30 09:46 UTC by oscarporsius

Added GPG encryption to the docker-backup.

2024-05-30 13:03 UTC, mprins commented on README.md
> +The GPG keys are used to encrypt and decrypt the backup files. You need to provide a "Public key file in .asc format" and place it in the keyfile folder. Make sure you name the file `public-key.asc`.
```suggestion
The GPG keys are used to encrypt and decrypt the backup files. You need to provide a "Public key file in .asc format" and place it in the keyfile folder. Make sure you name the file `public-key.asc`. Also make sure you rebuild the image with the new key. The private key is not. You need the private key to decrypt the backups. __make sure you keep the private key in a safe place. If you loose the private key that accompanies the public key, you will not be able to decrypt the backups!__ 
```

2024-05-30 13:03 UTC, mprins commented on README.md
> +The GPG keys are used to encrypt and decrypt the backup files. You need to provide a "Public key file in .asc format" and place it in the keyfile folder. Make sure you name the file `public-key.asc`.
> The private key is not.

Not what?

2024-05-30 13:23 UTC, oscarporsius commented on README.md
> +The GPG keys are used to encrypt and decrypt the backup files. You need to provide a "Public key file in .asc format" and place it in the keyfile folder. Make sure you name the file `public-key.asc`.
Should have been "The private key is not supposed to be used with this container!"

2024-06-03 14:11 UTC, matthijsln commented on Dockerfile
> +COPY keyfile/public-key.asc include
The public key should not be included in Docker image, but be a runtime environment variable. The script can write the environment variable to a file before calling `gpg`.

A public key has newlines but it shouldn't be a problem to configure a multiline environment variable using yaml or `\n` in an env-file. If multiline environment variables are still problematic the script can do some text mangling.

2024-06-03 14:14 UTC, matthijsln commented on include/encrypt.sh
> +        gpg --quiet --output "${file}.gpg" --encrypt --recipient-file "${KEYFILE}" "${file}"
If performance is slow `xargs` with the `-P` option can be used to parallellize encryption using multiple cores.

2024-06-03 14:15 UTC, matthijsln requested changes
See comments.

2024-06-07 08:35 UTC, matthijsln commented on include/utils.sh
> +upload_encrypted_backup() {
If leaving the unencrypted files on the host is intended for convenience, the duplicate code can still be reduced.

2024-06-13 13:40 UTC, matthijsln commented on .env
> +# This environment file is used to set up a Public GPG key for use in the encryption proces.
Just remove this file

2024-06-13 15:23 UTC, matthijsln requested changes

2024-06-13 15:23 UTC, matthijsln commented on include/encrypt.sh
>      mkdir -p /home/backup/include/keyfile
Use `$(dirname $KEYFILE)` or `${KEYFILE%/*}`

2024-06-13 15:23 UTC, matthijsln commented on test-compose.yml
> +# Add this to your Docker Compose configuration, or merge it by referencing this file in the COMPOSE_FILE environment
Remove

2024-06-13 15:23 UTC, matthijsln commented on README.md
> +### Step-by-Step Explanation:
Remove

2024-06-17 13:56 UTC, oscarporsius reviewed
lgtm

2024-06-17 13:56 UTC, oscarporsius reviewed
lgtm

2024-06-19 06:50 UTC, oscarporsius reviewed
lgtm

2024-06-21 11:17 UTC, merged